version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: biennc
      POSTGRES_PASSWORD: biennc123456
      POSTGRES_DB: school_management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL= postgresql://biennc:biennc123456@postgres:5432/school_management
    depends_on:
      - postgres

volumes:
  postgres_data:
